# Version de l'API Docker Compose à utiliser pour lire ce fichier
version: '3.8'
services:
  my_app:
    build:
      context: .
      dockerfile: multi-stage.dockerfile
    deploy:
      replicas: 4
    restart: always
    ports:
      - '8081'
    environment:
      - PING_LISTEN_PORT=8081
    networks:
      - front-network
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on: 
      - my_app
    networks:
      - front-network
networks:
  front-network:
    driver: bridge
